### PR TITLE
Run against THREDDS Test

### PR DESCRIPTION
**Pull request by jrleeman**
Run the examples against THREDDS test to help @lesserwhirls et al. shake down THREDDS 5.

### CODE REVIEW

**Comment by jrleeman** [comment]
I *think* this is ready to go pending verification that we are actually hitting thredds-test. Logs are.... nonexistent. If it becomes a regular issue we could make it an allowed failure, but I'm okay with it being in the required set of jobs for now.

**Comment by lesserwhirls** [comment]
Sweet! Thanks @jrleeman! It would be good to add thredds-dev as well (https://thredds-dev.unidata.ucar.edu), if it's not too much extra.

**Comment by jrleeman** [comment]
Yep, we can do that. As soon as I can prove that this is actually testing against `thredds-test` I'll refactor a bit.

**Comment by jrleeman** [comment]
Ok - should be ready to go now. Test and dev are allowed failures.

**Pull request merged**
