### PR TITLE
Adding 2019 version of the HurricaneTracker Notebook.

### PR DESCRIPTION
**Pull request by AodhanSweeney**

### CODE REVIEW

**Comment by kgoebber** [comment]
I was testing this PR and it doesn't appear that the BM.jpeg or images.json files get downloaded locally and when a person goes to download the .ipynb file they also won't get those files. Is there a way to include the ability to put a background image on from cartopy directly (meaning that it will download at runtime if necessary)?

**Comment by AodhanSweeney** [comment]
That's a good question. Poking around seems that it wouldn't be too hard to
download the files if they needed them, although that may bloat the
example, as in it may be a long walk for a short drink of water, and would
be showing more how to use cartopy's backgroud features as opposed to the
actual Hurricane Tracker. I will submit another PR soon that just uses a
typical canopy image as opposed to the Blue Marble image.

Thanks for noticing this!
Aodhan

**Comment by kgoebber** [comment]
Looks good now. Travis is failing on Satellite_Examply.py due to changes in GFS output available on remote servers. PR #121 handles the three cases that are impacted. Once that PR is in, we can rebase and get this one in.

**Comment by AodhanSweeney** [comment]
Okay sounds good

**Comment by kgoebber** [comment]
This PR should just need a rebase and clean up for commits and should be ready to go.

**Comment by AodhanSweeney** [comment]
Got it, I cleaned it up with a rebase and gave it another push

**Comment by kgoebber** [comment]
Having problems getting it to pass...only because of remote servers. Will try later tonight or tomorrow to get this in and merged.

**Comment by kgoebber** [comment]
Woo hoo - it's all green! PR merged! Thanks for the addition.

**Pull request merged**
