### PR TITLE
Standard 500 hPa Map Example

### PR DESCRIPTION
**Pull request by kgoebber**

### CODE REVIEW

**Comment by kgoebber** [comment]
Okay, so we'll probably kill this PR at some point. I'm working on examples that use example files instead of always relying on remote data access. The issue is that the files are too large for the NAM (~200 mb) and GFS (~130 mb) files.

**Comment by jrleeman** [comment]
As I remember this is sitting due to the need for a remote data store for the examples, correct. @dopplershift - what about hosting these on Unidata's webserver or an S3 bucket?

**Comment by kgoebber** [comment]
Sure thing…

http://bergeron.valpo.edu/python/example_data/



-- 
Kevin Goebbert, Ph.D.
Associate Professor of Meteorology
Kallay-Christopher Hall, 201-F
1809 Chapel Drive
Valparaiso, IN 46383

(219) 464-5517 <//(219)%20464-5517>
fax: (219) 548-7738 <//(219)%20548-7738>

https://kevingoebbert.youcanbook.me/

On November 20, 2018 at 5:21:53 PM, Ryan May (notifications@github.com)
wrote:

@kgoebber <https://github.com/kgoebber> Can you point me to the files? I'll
create a directory for example data on the main thredds server and we can
just host it there.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/Unidata/python-gallery/pull/82#issuecomment-440464846>,
or mute the thread

**Comment by kgoebber** [comment]
Status of getting the example data up on the Unidata THREDDS?

**Comment by dopplershift** [comment]
Data are now here: http://thredds.ucar.edu/thredds/catalog/casestudies/python-gallery/catalog.html

**Comment by dopplershift** [comment]
@kgoebber Can this be closed now that #92 (nee #91) has been merged?

**Comment by kgoebber** [comment]
Yes.

-- 
Kevin Goebbert, Ph.D.
Associate Professor of Meteorology
Kallay-Christopher Hall, 201-F
1809 Chapel Drive
Valparaiso, IN 46383

(219) 464-5517 <//(219)%20464-5517>
fax: (219) 548-7738 <//(219)%20548-7738>

https://kevingoebbert.youcanbook.me/

On February 19, 2019 at 4:01:33 PM, Ryan May (notifications@github.com)
wrote:

@kgoebber <https://github.com/kgoebber> Can this be closed now that #92
<https://github.com/Unidata/python-gallery/pull/92> (nee #91
<https://github.com/Unidata/python-gallery/pull/91>) has been merged?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/Unidata/python-gallery/pull/82#issuecomment-465328807>,
or mute the thread

**Pull request closed without merging**
