### PR TITLE
ENH: Add example of command line sounding plotter

### PR DESCRIPTION
**Pull request by dopplershift**
Written for the ELO field project, but might contain some useful nuggets for everyone.

### CODE REVIEW

**Comment by jrleeman** [comment]
Was this modified from the command line sounding plotter in the workshop materials?

**Comment by dopplershift** [comment]
Not modified from the workshop...because I forgot it was there. 🐑 Built from MetPy's Advanced SkewT example.

I want to make sure the rest of the community can benefit from the work I put into this. Can you think of another place to put this?

**Comment by jrleeman** [comment]
We'll have to discuss. I'm not sure where, but this doesn't seem like the right fit. Also it puts basically the same code in two repos.

**Comment by dopplershift** [comment]
Happy to discuss, but this script fits in with what I envision this repo to be: "Repository of examples showing off the use of Python for meteorology."--so I'm curious why you hesitate. There's a reason we renamed to "python-gallery" from "notebook-gallery".

**Comment by jrleeman** [comment]
We've decided after some offline discussion that things like this should live in a separate area and not be available as notebooks since it doesn't make sense. A `command line tools` section or similar.

**Comment by jrleeman** [comment]
It doesn't look like sphinx gallery has a way to turn off notebook generation 😞 so I'd say we need to make it bold and explicit at the beginning that this example needs to be download and run as a script.

**Pull request merged**
