### PR TITLE
Adds an observational data cross-section

### PR DESCRIPTION
**Pull request by kgoebber**
This example creates a contoured cross section of observational data by interpolated in both the vertical and horizontal. There are two functions that help accomplish this task that are at the beginning of the script.

### CODE REVIEW

**Comment by zbruick** [comment]
Running this with mpl 3.1.0, I get a non-inverted figure (100mb at bottom, 1000 at top). I can't figure out any variation of the ax.yaxis calls that get it to be as designed. Otherwise, this is a really useful example!
xsection_test

**Comment by kgoebber** [comment]
Ha! I’ll look into it. I just updated to matplotlib 3.1 in one of my
environments...

-- 
Kevin Goebbert, Ph.D.
Associate Professor of Meteorology
Kallay-Christopher Hall, 201-F
1809 Chapel Drive
Valparaiso, IN 46383

(219) 464-5517 <//(219)%20464-5517>
fax: (219) 548-7738 <//(219)%20548-7738>

https://kevingoebbert.youcanbook.me/

On June 10, 2019 at 9:44:11 AM, Zach Bruick (notifications@github.com)
wrote:

Running this with mpl 3.1.0, I get a non-inverted figure (100mb at bottom,
1000 at top). I can't figure out any variation of the ax.yaxis calls that
get it to be as designed. Otherwise, this is a really useful example!
[image: xsection_test]
<https://user-images.githubusercontent.com/29253833/59203423-cbdc2d80-8b5b-11e9-9c02-680a55d94372.png>

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/Unidata/python-gallery/pull/119?email_source=notifications&email_token=AE7BRVPIXZCZCS25N23AIV3PZZSDVA5CNFSM4HV2CUW2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODXKCOPY#issuecomment-500442943>,
or mute the thread

**Comment by kgoebber** [comment]
Okay, so I found that if I put the `ax.invert_yaxis()` after I set the limits and log nature of the yaxis, it works. Might this be the problem we are running into with all of the skew-T stuff in MetPy tests?

Pushed an update...see if you get the desired result.

**Comment by zbruick** [comment]
Yup that did the trick! I can look into the tests and see if that's our issue. I'll merge this once Travis passes.

**Comment by zbruick** [comment]
Not sure why Travis is failing now. I re-ran the build, but it failed again.

**Comment by kgoebber** [comment]
I think the problem comes in with the Isentropic Analysis example as it grabs data from a remote server and depending on time of day may time out. Let's give it until noon CDT and we can re-run to see if that fixes the issue.

**Pull request merged**
